version: "3.9"
services:
  mysql:
    container_name: prova-pratica-senai-mysql8
    image: mysql:8.3
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: senai
      MYSQL_USER: senai
      MYSQL_PASSWORD: senai123
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks: [ senai-net ]

  backend:
    container_name: prova-pratica-senai-backend
    build: ./backend
    depends_on:
      mysql:
          condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: default
    ports:
      - "8080:8080"
    networks: [ senai-net ]

  frontend:
    container_name: prova-pratica-senai-frontend
    build: ./frontend
    depends_on:
      - backend
    networks: [ senai-net ]

  nginx:
    image: nginx:1.27-alpine
    container_name: prova-pratica-senai-nginx
    depends_on:
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    networks: [ senai-net ]

volumes:
  mysql_data:

networks:
  senai-net:
    driver: bridge