spring:
  datasource:
    url: jdbc:mysql://localhost:3306/senai?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: senai
    password: senai123
    hikari:
      initialization-fail-timeout: -1