spring:
  datasource:
    url: jdbc:mysql://mysql:3306/senai?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: senai
    password: senai123
    hikari:
      initialization-fail-timeout: -1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization.write_dates_as_timestamps: false

server:
  port: 8080