spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization.write_dates_as_timestamps: false

server:
  port: 8080
  error:
    include-stacktrace: never
    include-message: always
    include-binding-errors: always